mlange-42/yarner

src/bin/main.rs, src/config/mod.rs, src/parser/md.rs, src/templates/Yarner-html.toml, src/templates/Yarner-md.toml, src/templates/Yarner-tex.toml
@adamreichold I think this is a sufficiently simple solution which solves the cases encountered so far.
You probably have some improvement suggestions regarding borrowing, `to_owned` etc. Also, there may be a more idiomatic solution than the for loop in `modify_path`.
Fixes #27.
=> Modify code paths

examples/default_setup/Yarner.toml, examples/default_setup/docs/README.md.md, examples/features_demo/Yarner.toml, examples/features_demo/docs/README.md.md, src/config/mod.rs, src/document/ast.rs, src/document/code.rs, src/document/mod.rs, src/document/tranclusion.rs, src/main.rs, src/parser/code.rs, src/parser/md.rs, src/parser/mod.rs, src/templates/Yarner-md.toml
=> Reverse mode

src/main.rs
`Fallible` might not look like a clear win ATM due to the additional `.into()` calls, but I think this will change when error propagation is used more systematically. For example,
```rust
match fs::read_to_string(file_name) {
Ok(config) => match toml::from_str(&config) {
Ok(config) => config,
Err(error) => {
return Err(format!(
"ERROR: Could not parse config file \"{}\": {}",
file_name, error
)
.into());
}
},
Err(error) => {
return Err(format!(
"ERROR: Could not read config file \"{}\": {}",
file_name, error
)
.into());
}
}
```
could be done as
```rust
fn read_config(path: &Path) -> Fallible<AnyConfig> {
let buf = fs::read_to_string(path)?;
let val = toml::from_str(&buf)?;
Ok(val)
}
...
let config = read_config(path).map_err(|err| format!("ERROR: Could not read config file \"{}\": {}", …
```
=> Replace more error types by Fallibe.

src/config.rs, src/main.rs
A lot of changes but all are purely clean up without any behavior modifications, except for removing the ERROR and --> prefixes from the program output and standardizing on "ERROR" in the main handler.
Note that as a general recommendation, `Option<&Borrowed>` is preferable to `&Option<Onwed>` as a function parameter. One could always go from the latter to the former via `.as_deref()`, but the other way around requires a temporary allocation.
Also note that I did not try to avoid cloning `config.paths` so much because of the allocations, but rather to avoid having to places in the program state where the same information is stored as this allows one to introduce bugs by modifying one but reading from the other.
=> Simplify config module

src/main.rs, src/util.rs
This might be leaning a bit into gamification, but it does drop one more temporary allocation and sets a bit of precedent towards better testing...
=> Move path mangling to util module and test it.

src/main.rs, src/parse.rs
=> Rework parser loop and link extraction

src/compile.rs, src/compile_reverse.rs, src/document/code.rs, src/document/mod.rs, src/document/text.rs, src/main.rs
=> Cleanup main, move stuff to compile-modules

src/compile.rs, src/compile_reverse.rs, src/files.rs, src/main.rs
=> Print everything except errors and warnings to stdout

src/lock.rs, src/main.rs
* Check for changes only if code output directory exists
* Better error message on file hashing error
=> Handle missing files/dirs during hashing

Cargo.lock, Cargo.toml, guide/src/links-and-transclusions.md, src/compile.rs, src/compile_reverse.rs, src/config.rs, src/parse.rs
=> Link correction during transclusion

guide/src/config-parser.md, src/config.rs, src/create/Yarner.toml, src/main.rs, src/parse.rs
Not really required, as it only adds missing language to code block opening fence.
=> Remove parser settings `default_language`

src/compile.rs, src/compile_reverse.rs, src/config.rs, src/document.rs, src/parse.rs, src/print.rs
=> Derive newline from source documents

src/compile/forward.rs, src/compile/mod.rs, src/compile/reverse.rs, src/document.rs, src/main.rs, src/parse.rs, src/print.rs
* Moved compile code into sub-modules
* Moved functions out of document module
=> Compile and document module

src/config.rs, src/parse.rs, src/print.rs, yarner-lib/src/document.rs, yarner-lib/src/lib.rs
=> Simple document

schemas/data.json, schemas/documents.json
=> Json schemas for data passed to and back from pre-processors

guide/src/preprocessors/writing.md, schemas/README.md
Guide section on json schemas, small README file for schemas
=> JSON schema docs

.travis.yml
=> Adapt CI to deploy executable without wrapping folder

src/compile/forward.rs, src/compile/reverse.rs, src/parse.rs, src/print.rs
=> Prevent circular macro calls and transclusions

src/parse.rs
* Stop with error on unclosed code blocks
=> Add integrity checks

.github/workflows/crates-io.yml, .github/workflows/publish.yml, Cargo.toml, README.md, guide/src/installation.md, guide/src/plugins/writing.md, yarner-lib/Cargo.toml, yarner-lib/README.md, yarner-lib/src/lib.rs
=> Publish crates

guide/src/watch-command.md, src/cmd.rs, src/compile/forward.rs, src/compile/reverse.rs, src/watch.rs
* Update the watch list if files changed
* Fix missing tracking/lock of transcluded files
=> Update watch list

guide/src/watch-command.md, src/cmd.rs, src/watch.rs
=> Do docs-only forward pass in watch mode
